[build-system]
requires = ["setuptools>=65.6.3", "wheel>=0.38.4"]

[project]
name = "jellyfin_migrator"
dynamic = ["version"]
description = "jellyfin migrator"
authors = [
    {name = "Max Zuidberg", email = "MMMZZZZ@users.noreply.github.com"},
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "kwutil>=0.3.4",
    "pyyaml>=6.0.2",
    "rich>=14.0.0",
    "scriptconfig>=0.8.2",
    "ubelt>=1.3.7",
]

[project.optional-dependencies]
tests = [
    "jellyfin-apiclient-python>=1.11.0",
    "pandas>=2.0.3",
]
#classifiers = []
#dependencies = []

[tool.setuptools.dynamic]
version = {attr = "jellyfin_migrator.__version__"}

[console_scripts]
jellyfin-migrator = "jellyfin_migrator.core:main"
jellyfin-id-scanner = "jellyfin_migrator.id_scanner"
